apiVersion: v1
kind: PersistentVolume
metadata:
  name: greatsql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/GreatSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: greatsql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
