apiVersion: v1
kind: PersistentVolume
metadata:
  name: deploy-greatsql-slaver-02-nfs-pv
  namespace: deploy-greatsql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.139.120
    path: /data/nfs/greatsql-slaver-02
  storageClassName: "nfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deploy-greatsql-slaver-02-nfs-pvc
  namespace: deploy-greatsql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 5Gi
  volumeName: deploy-greatsql-slaver-02-nfs-pv