apiVersion: v1
kind: Service
metadata:
  name: deploy-greatsql-master-svc
  namespace: deploy-greatsql
  labels:
    app: greatsql-master
spec:
  ports:
  - port: 3306
    name: greatsql
    targetPort: 3306
    nodePort: 30306
  selector:
    app: greatsql-master
  type: NodePort
  sessionAffinity: ClientIP