apiVersion: v1
kind: PersistentVolume
metadata:
  name: deploy-greatsql-slave-01-nfs-pv
  namespace: deploy-greatsql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
  # 注意修改IP地址和暴露的目录
    server: 192.168.139.120
    path: /data/nfs/greatsql-slave-01
  storageClassName: "nfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deploy-greatsql-slave-01-nfs-pvc
  namespace: deploy-greatsql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 5Gi
  volumeName: deploy-greatsql-slave-01-nfs-pv