apiVersion: v1
kind: PersistentVolume
metadata:
  name: deploy-greatsql-master-nfs-pv
  namespace: deploy-greatsql
spec:
  capacity:
    storage: 5Gi # pv的大小可自行修改
  accessModes:
    - ReadWriteMany
  nfs:
    # 注意修改IP地址和暴露的目录（如果不一样）
    server: 192.168.139.120
    path: /data/nfs/greatsql-master
  storageClassName: "nfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deploy-greatsql-master-nfs-pvc
  namespace: deploy-greatsql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 5Gi # pvc的大小可自行修改,和pv一样就好
  volumeName: deploy-greatsql-master-nfs-pv
