---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mgr
  namespace: greatsql
  labels:
    type: mgr
spec:
  storageClassName: pv-mgr
  capacity:
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /opt/k8s/storage/mgr
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mgr
  namespace: greatsql
spec:
  storageClassName: pv-mgr
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
