apiVersion: v1
kind: Service
metadata:
  name: mgr
  namespace: greatsql
  labels:
    app: mgr
spec:
  ports:
  - name: mysql-port
    port: 3306
    protocol: TCP
    targetPort: 3306
  clusterIP: None
  selector:
    app: mgr
